spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    web:
      pageable:
        default-page-size: 10

app.security.jwt.private-key: agt1fmZyZWVyaWRlcnIrCxILX2FoX1NFU1NJT0
app.security.owner.accessToken: NFQ1VSSVRZX1NBVkVEX1JFUVVFU1RzcgBBb3
bucket.name: freerider.appspot.com
