spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true

app.security.jwt.private-key: agt1fmZyZWVyaWRlcnIrCxILX2FoX1NFU1NJT0
app.security.owner.accessToken: NFQ1VSSVRZX1NBVkVEX1JFUVVFU1RzcgBBb3